---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:scc:github-arc
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - github-arc
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arc-runners-github-arc-scc
  namespace: github-arc-runners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:github-arc
subjects:
- kind: ServiceAccount
  name: github-arc-runner-set-gha-rs-no-permission
  namespace: github-arc-runners
